spring:
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/cnns}
  thymeleaf:
    cache: false # FÃ¼r schnellere Entwicklung

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics # Actuator Endpunkte